Funcionalidad 279/cambiar estado a varios alumnes
TallerDeDesarrollo-UCB/Nahual-ServicioDatos pull request #36
Opened 2020-11-23 23:03 UTC by JoseCarlosOliveraPeredo

2020-11-24 01:07 UTC, Kuko-CMLC requested changes

2020-11-24 01:07 UTC, Kuko-CMLC commented on src/app/services/estudianteService.js
> +    cambiarEstadoAlumnes: async(request, response) => {
request y response deberiamos cambiarlos a español.

2020-11-24 01:07 UTC, Kuko-CMLC commented on src/routes/estudiantes.js
> +        const result = await estudianteService.cambiarEstadoAlumnes(request, response);
Igual cambiar los request,reponse y result si se puede a español.

2020-11-24 01:07 UTC, Kuko-CMLC commented on src/routes/estudiantes.js
> +        console.log(error);
Deberiamos cambiar o eliminar este console.log.

2020-11-24 01:25 UTC, JPC07 commented on src/app/services/estudianteService.js
> +    cambiarEstadoAlumnes: async(request, response) => {
Concuerdo, deberia ser en español request y response

2020-11-24 01:25 UTC, JPC07 commented on src/app/services/estudianteService.js
> +        var estudiantes = request.body.estudiantes
En vez de request seria bueno cambiar a español.

2020-11-24 01:25 UTC, JPC07 commented on src/app/services/estudianteService.js
> +        var estado=request.body.estado
Falta espacio en el igual y creo que punto y coma -> ;

2020-11-24 01:25 UTC, JPC07 commented on src/app/services/estudianteService.js
> +                    resultado.push({ Operacion: "Se cambio el estado correctamente de estudiante: "+estudianteEncontrado.nombreCompleto});
Dar formato, falta espacio en el +

2020-11-24 01:25 UTC, JPC07 commented on src/routes/estudiantes.js
> +        const result = await estudianteService.cambiarEstadoAlumnes(request, response);
Concuerdo, deberia ser español el result, request y response.

2020-11-24 01:25 UTC, JPC07 commented on src/app/services/estudianteService.js
>  module.exports = EstudianteService;
Creo que esto se deberia mejorar, ya que esta en  una mezcla de Español e ingles. Sin embargo podrian coordinar eso con el equipo 4 ya que ellos estan trabajando en el mismo repo.

2020-11-24 23:15 UTC, GamalSerhanOporto commented on src/app/services/estudianteService.js
> +    cambiarEstadoAlumnes: async(request, response) => {
estoy de acuerdo.

2020-11-24 23:17 UTC, GamalSerhanOporto reviewed
Fuera de los comentarios de Manu y Jey sobre todo con request, response y el idioma de eso no tengo observaciones.

2020-11-25 00:48 UTC, FidelRojas approved these changes

2020-11-25 16:52 UTC, melissafg approved these changes
arreglar los comentarios de jeymi y manuel, aparte de eso no hay más comentarios.

2020-11-25 16:59 UTC, PabloCanelas approved these changes

2020-11-25 22:26 UTC, johancarlos commented on src/app/services/estudianteService.js
>  module.exports = EstudianteService;
ok, genial. Coordinaremos esta observación, para ver de resolverlo en otra tarea/rama

2020-11-25 23:30 UTC, GamalSerhanOporto approved these changes

2020-11-27 11:30 UTC, JPC07 commented on src/app/services/estudianteService.js
>  module.exports = EstudianteService;
Si no se puede cambiar, lo dejamos para un sigueinte sprint o com unatarea que puedan hacer el siguiente semestre .

2020-11-30 01:19 UTC, merged